name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: make test/unit
      - run: make -j$(( $(nproc) + 1 ))
      - uses: actions/upload-artifact@v4
        with:
          name: Terraform.tgz
          path: .build/latest/Terraform.tgz

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Terraform.tgz

      - uses: softprops/action-gh-release@v2
        with:
          files: Terraform.tgz
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.CI_USER_ACCESS_TOKEN }}